package com.example.praxis.apiquickstart.config;

import com.example.praxis.apiquickstart.ApiQuickstartApplication;
import com.example.praxis.apiquickstart.security.JwtTokenService;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;

import java.net.URI;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@SpringBootTest(
        classes = ApiQuickstartApplication.class,
        webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
        properties = {
                "app.rate-limit.enabled=false",
                "app.security.config-origin-restriction.enabled=false",
                "app.security.read-open=true",
                "app.security.write-disabled=false",
                "app.security.schemas-aggregator.enabled=true",
                "app.security.csrf.disable=true",
                "app.session.cookie-name=SESSION",
                "app.session.secure=false",
                "app.session.samesite=Lax",
                "praxis.stats.enabled=true",
                "praxis.ai.provider=mock",
                "spring.ai.embedding.provider=mock",
                "spring.ai.openai.api-key=dummy",
                "praxis.ai.rag.vector-store.enabled=false",
                "praxis.ai.registry.bootstrap.enabled=false",
                "praxis.ai.registry.health.enabled=false",
                "spring.ai.vectorstore.pgvector.initialize-schema=false",
                "spring.ai.vectorstore.pgvector.vector-table-validations-enabled=false",
                "spring.flyway.enabled=false",
                "spring.datasource.url=jdbc:h2:mem:quickstart_eventos_folha_api;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
                "spring.datasource.driver-class-name=org.h2.Driver",
                "spring.datasource.username=sa",
                "spring.datasource.password=",
                "config.datasource.url=jdbc:h2:mem:quickstart_eventos_folha_config;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
                "config.datasource.driver-class-name=org.h2.Driver",
                "config.datasource.username=sa",
                "config.datasource.password=",
                "spring.jpa.hibernate.ddl-auto=none"
        }
)
class EventosFolhaPilotIntegrationTest {

    @Autowired
    private TestRestTemplate restTemplate;

    @Autowired
    @Qualifier("apiJdbcTemplate")
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private JwtTokenService jwtTokenService;

    @MockBean(name = "ragVectorStore")
    private VectorStore ragVectorStore;

    @MockBean
    private DomainRuleApprovalPolicyResolver approvalPolicyResolver;

    @MockBean
    private DomainRuleBackendValidationPolicyResolver backendValidationPolicyResolver;

    @MockBean
    private DomainRuleOptionSourcePolicyResolver optionSourcePolicyResolver;

    @MockBean
    private DomainRuleWorkflowActionPolicyResolver workflowActionPolicyResolver;

    @BeforeEach
    void seedEventosFolhaTables() {
        jdbcTemplate.execute("drop table if exists public.eventos_folha");
        jdbcTemplate.execute("drop table if exists public.folhas_pagamento");

        jdbcTemplate.execute("""
                create table public.folhas_pagamento (
                    id integer generated by default as identity primary key,
                    ano integer not null,
                    mes integer not null,
                    salario_bruto numeric(19, 2) not null,
                    total_descontos numeric(19, 2) not null,
                    salario_liquido numeric(19, 2) not null,
                    data_pagamento date not null,
                    funcionario_id integer not null
                )
                """);

        jdbcTemplate.execute("""
                create table public.eventos_folha (
                    id integer generated by default as identity primary key,
                    descricao varchar(255) not null,
                    tipo varchar(100) not null,
                    valor numeric(19, 2) not null,
                    folha_pagamento_id integer not null,
                    status varchar(20)
                )
                """);

        jdbcTemplate.update("""
                insert into public.folhas_pagamento
                    (id, ano, mes, salario_bruto, total_descontos, salario_liquido, data_pagamento, funcionario_id)
                values
                    (1, 2026, 3, 10000.00, 1200.00, 8800.00, DATE '2026-03-31', 1)
                """);

        jdbcTemplate.update("""
                insert into public.eventos_folha
                    (id, descricao, tipo, valor, folha_pagamento_id, status)
                values
                    (1, 'INSS', 'DESCONTO', 123.45, 1, 'PENDENTE')
                """);
    }

    @Test
    void shouldExposeCanonicalPilotDiscoveryForEventosFolha() throws Exception {
        JsonNode surfacesCatalog = body(restTemplate.getForEntity(
                "/schemas/surfaces?resource=human-resources.eventos-folha",
                String.class
        ));
        assertEquals("human-resources.eventos-folha", surfacesCatalog.path("resourceKey").asText());
        assertEquals("/api/human-resources/eventos-folha", surfacesCatalog.path("resourcePath").asText());
        assertEquals("human-resources", surfacesCatalog.path("group").asText());
        assertNotNull(findById(surfacesCatalog.path("surfaces"), "create"));
        assertNotNull(findById(surfacesCatalog.path("surfaces"), "detail"));

        JsonNode createSurface = findById(surfacesCatalog.path("surfaces"), "create");
        assertEquals("COLLECTION", createSurface.path("scope").asText());
        assertEquals("POST", createSurface.path("method").asText());
        assertTrue(createSurface.path("schemaUrl").asText().contains("path=%2Fapi%2Fhuman-resources%2Feventos-folha"));
        assertTrue(createSurface.path("schemaUrl").asText().contains("schemaType=request"));

        JsonNode actionsCatalog = body(restTemplate.getForEntity(
                "/schemas/actions?resource=human-resources.eventos-folha",
                String.class
        ));
        assertEquals("human-resources.eventos-folha", actionsCatalog.path("resourceKey").asText());
        assertEquals(1, actionsCatalog.path("actions").size());

        JsonNode bulkApprove = findById(actionsCatalog.path("actions"), "bulk-approve");
        assertNotNull(bulkApprove);
        assertEquals("COLLECTION", bulkApprove.path("scope").asText());
        assertEquals("POST", bulkApprove.path("method").asText());
        assertEquals("/api/human-resources/eventos-folha/actions/bulk-approve", bulkApprove.path("path").asText());
        assertTrue(bulkApprove.path("requestSchemaUrl").asText().contains("schemaType=request"));
        assertTrue(bulkApprove.path("responseSchemaUrl").asText().contains("schemaType=response"));

        JsonNode collectionActions = body(restTemplate.getForEntity(
                "/api/human-resources/eventos-folha/actions",
                String.class
        ));
        assertEquals("human-resources.eventos-folha", collectionActions.path("resourceKey").asText());
        assertNotNull(findById(collectionActions.path("actions"), "bulk-approve"));

        JsonNode collectionCapabilities = body(restTemplate.getForEntity(
                "/api/human-resources/eventos-folha/capabilities",
                String.class
        ));
        assertEquals("human-resources.eventos-folha", collectionCapabilities.path("resourceKey").asText());
        assertEquals("/api/human-resources/eventos-folha", collectionCapabilities.path("resourcePath").asText());
        assertEquals("api-human-resources-eventos-folha", collectionCapabilities.path("group").asText());
        assertTrue(collectionCapabilities.path("canonicalOperations").path("create").asBoolean());
        assertTrue(collectionCapabilities.path("canonicalOperations").path("update").asBoolean());
        assertTrue(collectionCapabilities.path("canonicalOperations").path("delete").asBoolean());
        assertTrue(collectionCapabilities.path("canonicalOperations").path("filter").asBoolean());
        assertTrue(collectionCapabilities.path("canonicalOperations").path("export").asBoolean());
        assertTrue(collectionCapabilities.path("operations").path("create").path("supported").asBoolean());
        assertEquals("COLLECTION", collectionCapabilities.path("operations").path("create").path("scope").asText());
        assertEquals("POST", collectionCapabilities.path("operations").path("create").path("preferredMethod").asText());
        JsonNode exportOperation = collectionCapabilities.path("operations").path("export");
        assertTrue(exportOperation.path("supported").asBoolean());
        assertEquals("COLLECTION", exportOperation.path("scope").asText());
        assertEquals("POST", exportOperation.path("preferredMethod").asText());
        assertEquals("export", exportOperation.path("preferredRel").asText());
        assertEquals("csv", exportOperation.path("formats").get(0).asText());
        assertEquals("json", exportOperation.path("formats").get(1).asText());
        assertEquals("auto", exportOperation.path("scopes").get(0).asText());
        assertEquals("selected", exportOperation.path("scopes").get(1).asText());
        assertEquals("filtered", exportOperation.path("scopes").get(2).asText());
        assertEquals("currentPage", exportOperation.path("scopes").get(3).asText());
        assertEquals("all", exportOperation.path("scopes").get(4).asText());
        assertEquals(500, exportOperation.path("maxRows").path("csv").asInt());
        assertEquals(500, exportOperation.path("maxRows").path("json").asInt());
        assertFalse(exportOperation.path("async").asBoolean());
        assertTrue(collectionCapabilities.path("operations").path("view").path("supported").asBoolean());
        assertEquals("GET", collectionCapabilities.path("operations").path("view").path("preferredMethod").asText());
        assertTrue(collectionCapabilities.path("operations").path("edit").path("supported").asBoolean());
        assertEquals("PUT", collectionCapabilities.path("operations").path("edit").path("preferredMethod").asText());
        assertTrue(collectionCapabilities.path("operations").path("delete").path("supported").asBoolean());
        assertEquals("DELETE", collectionCapabilities.path("operations").path("delete").path("preferredMethod").asText());
        assertNotNull(findById(collectionCapabilities.path("surfaces"), "create"));
        assertNotNull(findById(collectionCapabilities.path("actions"), "bulk-approve"));

        JsonNode requestSchema = body(restTemplate.getForEntity(
                "/schemas/filtered?path={path}&operation=post&schemaType=request",
                String.class,
                "/api/human-resources/eventos-folha"
        ));
        assertTrue(requestSchema.path("properties").has("descricao"));
        assertEquals("Descrição", requestSchema.path("properties").path("descricao").path("x-ui").path("label").asText());
        assertTrue(requestSchema.path("properties").has("tipo"));
        assertTrue(requestSchema.path("properties").has("valor"));
        assertTrue(requestSchema.path("properties").has("folhaPagamentoId"));
        assertFalse(requestSchema.path("properties").has("id"));
        assertFalse(requestSchema.path("properties").has("folhaPagamentoNome"));
        JsonNode folhaUi = requestSchema.path("properties").path("folhaPagamentoId").path("x-ui");
        JsonNode payrollOptionSource = folhaUi.path("optionSource");
        assertEquals("Folha à qual o evento pertence.", folhaUi.path("helpText").asText());
        assertEquals("entityLookup", folhaUi.path("controlType").asText());
        assertEquals("/api/human-resources/folhas-pagamento/option-sources/payroll/options/filter",
                folhaUi.path("endpoint").asText());
        assertEquals("payroll", payrollOptionSource.path("key").asText());
        assertEquals("RESOURCE_ENTITY", payrollOptionSource.path("type").asText());
        assertEquals("/api/human-resources/folhas-pagamento", payrollOptionSource.path("resourcePath").asText());
        assertEquals("payroll", payrollOptionSource.path("entityKey").asText());
        assertTrue(payrollOptionSource.path("capabilities").path("filter").asBoolean());
        assertTrue(payrollOptionSource.path("capabilities").path("byIds").asBoolean());

        JsonNode bulkApproveRequestSchema = body(restTemplate.getForEntity(
                "/schemas/filtered?path={path}&operation=post&schemaType=request",
                String.class,
                "/api/human-resources/eventos-folha/actions/bulk-approve"
        ));
        JsonNode idsUi = bulkApproveRequestSchema.path("properties").path("ids").path("x-ui");
        assertEquals("IDs dos eventos", idsUi.path("label").asText());
        assertEquals("Ação", idsUi.path("group").asText());

        JsonNode payrollOptions = body(restTemplate.postForEntity(
                "/api/human-resources/folhas-pagamento/option-sources/payroll/options/filter",
                authorizedJson("{}", jwtTokenService.generate("admin", "ADMIN")),
                String.class
        ));
        assertEquals(1, payrollOptions.path("content").size());
        assertEquals(1, payrollOptions.path("content").get(0).path("id").asInt());
        assertEquals("2026", payrollOptions.path("content").get(0).path("label").asText());
        assertEquals("3 - 2026-03-31", payrollOptions.path("content").get(0).path("extra").path("description").asText());

        JsonNode selectedPayroll = objectMapper.readTree(restTemplate.getForObject(
                "/api/human-resources/folhas-pagamento/option-sources/payroll/options/by-ids?ids=1",
                String.class
        ));
        assertEquals(1, selectedPayroll.size());
        assertEquals("2026", selectedPayroll.get(0).path("label").asText());

        JsonNode itemSurfaces = body(restTemplate.getForEntity(
                "/api/human-resources/eventos-folha/1/surfaces",
                String.class
        ));
        assertEquals(1, itemSurfaces.path("resourceId").asInt());
        assertNotNull(findById(itemSurfaces.path("surfaces"), "detail"));
        assertNotNull(findById(itemSurfaces.path("surfaces"), "edit"));

        ResponseEntity<String> itemActions = restTemplate.getForEntity(
                "/api/human-resources/eventos-folha/1/actions",
                String.class
        );
        assertEquals(HttpStatus.NOT_FOUND, itemActions.getStatusCode());

        JsonNode itemCapabilities = body(restTemplate.getForEntity(
                "/api/human-resources/eventos-folha/1/capabilities",
                String.class
        ));
        assertEquals(1, itemCapabilities.path("resourceId").asInt());
        assertTrue(itemCapabilities.path("operations").path("view").path("supported").asBoolean());
        assertEquals("GET", itemCapabilities.path("operations").path("view").path("preferredMethod").asText());
        assertTrue(itemCapabilities.path("operations").path("edit").path("supported").asBoolean());
        assertEquals("PUT", itemCapabilities.path("operations").path("edit").path("preferredMethod").asText());
        assertTrue(itemCapabilities.path("operations").path("delete").path("supported").asBoolean());
        assertNotNull(findById(itemCapabilities.path("surfaces"), "detail"));
        assertEquals(0, itemCapabilities.path("actions").size());
    }

    @Test
    void shouldExposeHypermediaDiscoveryLinksForEventosFolhaCollectionAndItem() throws Exception {
        JsonNode collectionEnvelope = body(restTemplate.getForEntity(
                "/api/human-resources/eventos-folha/all",
                String.class
        ));
        assertTrue(collectionEnvelope.has("_links"));
        assertTrue(collectionEnvelope.path("_links").isObject());
        assertTrue(collectionEnvelope.path("data").path(0).path("_links").isObject());
        assertFalse(collectionEnvelope.path("data").path(0).path("_links").has("create"));

        String collectionSurfacesHref = findLinkHref(collectionEnvelope, "surfaces");
        String collectionActionsHref = findLinkHref(collectionEnvelope, "actions");
        String collectionCapabilitiesHref = findLinkHref(collectionEnvelope, "capabilities");
        String collectionExportHref = findLinkHref(collectionEnvelope, "export");

        assertNotNull(collectionSurfacesHref);
        assertNotNull(collectionActionsHref);
        assertNotNull(collectionCapabilitiesHref);
        assertNotNull(collectionExportHref);

        JsonNode collectionSurfaces = body(getHref(collectionSurfacesHref));
        JsonNode createSurface = findById(collectionSurfaces.path("surfaces"), "create");
        assertNotNull(createSurface);
        assertEquals("COLLECTION", createSurface.path("scope").asText());

        JsonNode createSchema = body(getHref(createSurface.path("schemaUrl").asText()));
        assertTrue(createSchema.path("properties").has("descricao"));
        assertTrue(createSchema.path("properties").has("tipo"));
        assertTrue(createSchema.path("properties").has("valor"));

        JsonNode collectionActions = body(getHref(collectionActionsHref));
        JsonNode bulkApprove = findById(collectionActions.path("actions"), "bulk-approve");
        assertNotNull(bulkApprove);
        assertEquals("COLLECTION", bulkApprove.path("scope").asText());

        JsonNode bulkApproveRequestSchema = body(getHref(bulkApprove.path("requestSchemaUrl").asText()));
        assertTrue(bulkApproveRequestSchema.path("properties").has("ids"));

        JsonNode collectionCapabilities = body(getHref(collectionCapabilitiesHref));
        assertTrue(collectionCapabilities.path("canonicalOperations").path("export").asBoolean());
        assertTrue(collectionCapabilities.path("operations").path("export").path("supported").asBoolean());
        assertEquals("csv", collectionCapabilities.path("operations").path("export").path("formats").get(0).asText());
        assertTrue(collectionCapabilities.path("operations").path("create").path("supported").asBoolean());
        assertEquals("POST", collectionCapabilities.path("operations").path("create").path("preferredMethod").asText());
        assertNotNull(findById(collectionCapabilities.path("surfaces"), "create"));
        assertNotNull(findById(collectionCapabilities.path("actions"), "bulk-approve"));

        JsonNode itemEnvelope = body(restTemplate.getForEntity(
                "/api/human-resources/eventos-folha/1",
                String.class
        ));
        assertTrue(itemEnvelope.has("_links"));
        assertTrue(itemEnvelope.path("_links").isObject());
        assertFalse(itemEnvelope.path("_links").has("create"));

        String itemSurfacesHref = findLinkHref(itemEnvelope, "surfaces");
        String itemActionsHref = findLinkHref(itemEnvelope, "actions");
        String itemCapabilitiesHref = findLinkHref(itemEnvelope, "capabilities");

        assertNotNull(itemSurfacesHref);
        assertNull(itemActionsHref);
        assertNotNull(itemCapabilitiesHref);

        JsonNode itemSurfaces = body(getHref(itemSurfacesHref));
        assertNotNull(findById(itemSurfaces.path("surfaces"), "detail"));
        assertNotNull(findById(itemSurfaces.path("surfaces"), "edit"));

        JsonNode itemCapabilities = body(getHref(itemCapabilitiesHref));
        assertTrue(itemCapabilities.path("operations").path("view").path("supported").asBoolean());
        assertTrue(itemCapabilities.path("operations").path("edit").path("supported").asBoolean());
        assertNotNull(findById(itemCapabilities.path("surfaces"), "detail"));
        assertEquals(0, itemCapabilities.path("actions").size());
    }

    @Test
    void shouldExportEventosFolhaCollectionAsCsv() {
        ResponseEntity<String> exported = restTemplate.exchange(
                "/api/human-resources/eventos-folha/export",
                HttpMethod.POST,
                authorizedJson("""
                        {
                          "format": "csv",
                          "scope": "selected",
                          "fileName": "eventos-folha-piloto.csv",
                          "selection": {
                            "keyField": "id",
                            "selectedKeys": [1]
                          },
                          "fields": [
                            { "key": "id", "label": "ID" },
                            { "key": "descricao", "label": "Descricao" },
                            { "key": "valor", "label": "Valor" }
                          ],
                          "includeHeaders": true
                        }
                        """, jwtTokenService.generate("admin", "ADMIN")),
                String.class
        );

        assertEquals(HttpStatus.OK, exported.getStatusCode());
        assertNotNull(exported.getHeaders().getContentType());
        assertEquals("text", exported.getHeaders().getContentType().getType());
        assertEquals("csv", exported.getHeaders().getContentType().getSubtype());
        assertTrue(exported.getHeaders().getFirst(HttpHeaders.CONTENT_DISPOSITION)
                .contains("eventos-folha-piloto.csv"));
        assertEquals("1", exported.getHeaders().getFirst("X-Export-Row-Count"));
        assertEquals("""
                "ID","Descricao","Valor"\r
                "1","INSS","123.45"
                """.stripTrailing(), exported.getBody());
    }

    @Test
    void shouldExportEventosFolhaCollectionAsJson() throws Exception {
        ResponseEntity<String> exported = restTemplate.exchange(
                "/api/human-resources/eventos-folha/export",
                HttpMethod.POST,
                authorizedJson("""
                        {
                          "format": "json",
                          "scope": "selected",
                          "fileName": "eventos-folha-piloto.json",
                          "selection": {
                            "keyField": "id",
                            "selectedKeys": [1]
                          },
                          "fields": [
                            { "key": "id", "label": "ID" },
                            { "key": "descricao", "label": "Descricao" },
                            { "key": "valor", "label": "Valor" }
                          ]
                        }
                        """, jwtTokenService.generate("admin", "ADMIN")),
                String.class
        );

        assertEquals(HttpStatus.OK, exported.getStatusCode());
        assertNotNull(exported.getHeaders().getContentType());
        assertEquals(MediaType.APPLICATION_JSON, exported.getHeaders().getContentType());
        assertTrue(exported.getHeaders().getFirst(HttpHeaders.CONTENT_DISPOSITION)
                .contains("eventos-folha-piloto.json"));
        assertEquals("1", exported.getHeaders().getFirst("X-Export-Row-Count"));

        JsonNode rows = objectMapper.readTree(exported.getBody());
        assertEquals(1, rows.size());
        assertEquals(1, rows.get(0).path("id").asInt());
        assertEquals("INSS", rows.get(0).path("descricao").asText());
        assertEquals("123.45", rows.get(0).path("valor").asText());
    }

    @Test
    void shouldExposeTruncationHeadersWhenCollectionExportIsLimited() {
        jdbcTemplate.update("""
                insert into public.eventos_folha
                    (id, descricao, tipo, valor, folha_pagamento_id, status)
                values
                    (2, 'IRRF', 'DESCONTO', 99.99, 1, 'PENDENTE')
                """);

        ResponseEntity<String> exported = restTemplate.exchange(
                "/api/human-resources/eventos-folha/export",
                HttpMethod.POST,
                authorizedJson("""
                        {
                          "format": "csv",
                          "scope": "all",
                          "maxRows": 1,
                          "fields": [
                            { "key": "id", "label": "ID" },
                            { "key": "descricao", "label": "Descricao" }
                          ]
                        }
                        """, jwtTokenService.generate("admin", "ADMIN")),
                String.class
        );

        assertEquals(HttpStatus.OK, exported.getStatusCode());
        assertEquals("1", exported.getHeaders().getFirst("X-Export-Row-Count"));
        assertEquals("true", exported.getHeaders().getFirst("X-Export-Truncated"));
        assertEquals("1", exported.getHeaders().getFirst("X-Export-Max-Rows"));
        assertEquals("2", exported.getHeaders().getFirst("X-Export-Candidate-Row-Count"));
        assertTrue(exported.getHeaders().getFirst("X-Export-Warnings").contains("Export truncated to 1 rows from 2 matching rows."));
    }

    @Test
    void shouldRejectEventosFolhaExportWhenRequestedFieldsAreNotSupported() {
        ResponseEntity<String> exported = restTemplate.exchange(
                "/api/human-resources/eventos-folha/export",
                HttpMethod.POST,
                authorizedJson("""
                        {
                          "format": "csv",
                          "scope": "selected",
                          "selection": {
                            "keyField": "id",
                            "selectedKeys": [1]
                          },
                          "fields": [
                            { "key": "senhaInterna", "label": "Senha interna" }
                          ]
                        }
                        """, jwtTokenService.generate("admin", "ADMIN")),
                String.class
        );

        assertEquals(HttpStatus.BAD_REQUEST, exported.getStatusCode());
        assertTrue(exported.getBody().contains("One or more requested export fields are not supported by this resource."));
    }

    @Test
    void shouldExecuteBulkApproveWorkflowWithStateValidation() throws Exception {
        ResponseEntity<String> approved = restTemplate.exchange(
                "/api/human-resources/eventos-folha/actions/bulk-approve",
                HttpMethod.POST,
                authorizedJson("""
                        {
                          "ids": [1]
                        }
                        """, jwtTokenService.generate("admin", "ADMIN")),
                String.class
        );
        JsonNode approvedBody = body(approved);
        assertEquals(1, approvedBody.path("data").path("processed").asInt());
        assertEquals(0, approvedBody.path("data").path("failed").asInt());
        assertEquals("APROVADO", jdbcTemplate.queryForObject(
                "select status from public.eventos_folha where id = 1",
                String.class
        ));

        ResponseEntity<String> blockedByState = restTemplate.exchange(
                "/api/human-resources/eventos-folha/actions/bulk-approve",
                HttpMethod.POST,
                authorizedJson("""
                        {
                          "ids": [1]
                        }
                        """, jwtTokenService.generate("admin", "ADMIN")),
                String.class
        );
        JsonNode blockedByStateBody = body(blockedByState);
        assertEquals(0, blockedByStateBody.path("data").path("processed").asInt());
        assertEquals(1, blockedByStateBody.path("data").path("failed").asInt());
        assertEquals("State not allowed: APROVADO", blockedByStateBody.path("data").path("details").get(0).path("error").asText());
    }

    private JsonNode body(ResponseEntity<String> response) throws Exception {
        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertNotNull(response.getBody());
        return objectMapper.readTree(response.getBody());
    }

    private HttpEntity<String> authorizedJson(String json, String token) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.add(HttpHeaders.COOKIE, "SESSION=" + token);
        return new HttpEntity<>(json, headers);
    }

    private JsonNode findById(JsonNode items, String id) {
        for (JsonNode item : items) {
            if (id.equals(item.path("id").asText())) {
                return item;
            }
        }
        return null;
    }

    private String findLinkHref(JsonNode envelope, String rel) {
        JsonNode links = envelope.path("_links");
        if (!links.isObject()) {
            return null;
        }

        JsonNode halLink = links.path(rel);
        return halLink.isObject() ? halLink.path("href").asText(null) : null;
    }

    private ResponseEntity<String> getHref(String href) {
        return restTemplate.getForEntity(URI.create(href), String.class);
    }
}
