package com.example.praxis.apiquickstart.config;

import com.example.praxis.apiquickstart.ApiQuickstartApplication;
import com.example.praxis.apiquickstart.security.JwtTokenService;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.http.client.SimpleClientHttpRequestFactory;
import org.springframework.jdbc.core.JdbcTemplate;

import java.io.ByteArrayInputStream;
import java.time.Duration;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@SpringBootTest(
        classes = ApiQuickstartApplication.class,
        webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
        properties = {
                "app.rate-limit.enabled=false",
                "app.security.config-origin-restriction.enabled=false",
                "app.security.read-open=true",
                "app.security.write-disabled=false",
                "app.security.schemas-aggregator.enabled=true",
                "app.security.csrf.disable=true",
                "app.session.cookie-name=SESSION",
                "app.session.secure=false",
                "app.session.samesite=Lax",
                "praxis.stats.enabled=true",
                "praxis.ai.provider=mock",
                "spring.ai.embedding.provider=mock",
                "spring.ai.openai.api-key=dummy",
                "praxis.ai.rag.vector-store.enabled=false",
                "praxis.ai.registry.bootstrap.enabled=false",
                "praxis.ai.registry.health.enabled=false",
                "spring.ai.vectorstore.pgvector.initialize-schema=false",
                "spring.ai.vectorstore.pgvector.vector-table-validations-enabled=false",
                "spring.flyway.enabled=false",
                "spring.datasource.url=jdbc:h2:mem:quickstart_funcionarios_export_api;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
                "spring.datasource.driver-class-name=org.h2.Driver",
                "spring.datasource.username=sa",
                "spring.datasource.password=",
                "config.datasource.url=jdbc:h2:mem:quickstart_funcionarios_export_config;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
                "config.datasource.driver-class-name=org.h2.Driver",
                "config.datasource.username=sa",
                "config.datasource.password=",
                "spring.jpa.hibernate.ddl-auto=none"
        }
)
class FuncionarioExportSmokeHttpTest {

    @Autowired
    private TestRestTemplate restTemplate;

    @Autowired
    @Qualifier("apiJdbcTemplate")
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private JwtTokenService jwtTokenService;

    @MockBean(name = "ragVectorStore")
    private VectorStore ragVectorStore;

    @BeforeEach
    void seedFuncionarioTables() {
        SimpleClientHttpRequestFactory requestFactory = new SimpleClientHttpRequestFactory();
        requestFactory.setConnectTimeout(Duration.ofSeconds(10));
        requestFactory.setReadTimeout(Duration.ofSeconds(60));
        restTemplate.getRestTemplate().setRequestFactory(requestFactory);

        jdbcTemplate.execute("drop table if exists public.funcionarios");
        jdbcTemplate.execute("drop table if exists public.cargos");
        jdbcTemplate.execute("drop table if exists public.departamentos");

        jdbcTemplate.execute("""
                create table public.cargos (
                    id integer generated by default as identity primary key,
                    nome varchar(120) not null,
                    nivel varchar(60) not null,
                    descricao varchar(255),
                    salario_minimo numeric(19, 2),
                    salario_maximo numeric(19, 2)
                )
                """);
        jdbcTemplate.execute("""
                create table public.departamentos (
                    id integer generated by default as identity primary key,
                    nome varchar(120) not null,
                    codigo varchar(20) not null,
                    responsavel_id integer
                )
                """);
        jdbcTemplate.execute("""
                create table public.funcionarios (
                    id integer generated by default as identity primary key,
                    version bigint not null default 0,
                    nome_completo varchar(200) not null,
                    cpf varchar(11) not null,
                    data_nascimento date not null,
                    email varchar(200) not null,
                    telefone varchar(30) not null,
                    salario numeric(19, 2) not null,
                    data_admissao date not null,
                    ativo boolean not null,
                    cargo_id integer not null,
                    departamento_id integer not null,
                    foto_perfil_url varchar(255),
                    estado_civil varchar(40),
                    pais_nascimento varchar(80),
                    cidade_nascimento varchar(80)
                )
                """);

        jdbcTemplate.update("""
                insert into public.cargos (id, nome, nivel, descricao, salario_minimo, salario_maximo)
                values (1, 'Agente', 'Senior', 'Cargo operacional', 1000.00, 99000.00)
                """);
        jdbcTemplate.update("""
                insert into public.departamentos (id, nome, codigo, responsavel_id)
                values (1, 'Operacoes', 'OPS', null)
                """);
        jdbcTemplate.update("""
                insert into public.funcionarios
                    (id, nome_completo, cpf, data_nascimento, email, telefone, salario, data_admissao,
                     ativo, cargo_id, departamento_id, estado_civil)
                values
                    (1, 'Ana Silva', '11111111111', DATE '1988-01-10', 'ana@example.com', '+5511999999999',
                     41000.00, DATE '2022-06-13', true, 1, 1, 'CASADO'),
                    (2, 'Bruno Lima', '22222222222', DATE '1985-02-20', 'bruno@example.com', '+5511888888888',
                     95000.00, DATE '2010-02-01', false, 1, 1, 'SOLTEIRO')
                """);
    }

    @Test
    void shouldExportFuncionariosCsvWithGovernedExcelFriendlyFormatting() {
        ResponseEntity<String> exported = postExport("""
                {
                  "format": "csv",
                  "scope": "currentPage",
                  "includeHeaders": true,
                  "applyFormatting": true,
                  "fields": [
                    { "key": "ativo", "label": "Status", "visible": true, "exportable": true },
                    { "key": "salario", "label": "Salario", "visible": true, "exportable": true },
                    { "key": "dataAdmissao", "label": "Admissao", "visible": true, "exportable": true }
                  ],
                  "pagination": { "pageIndex": 0, "pageNumber": 0, "pageSize": 2 },
                  "sort": [{ "field": "salario", "direction": "desc" }],
                  "formatOptions": { "csv": { "excelCompatibility": true } },
                  "localization": { "locale": "pt-BR", "timeZone": "America/Sao_Paulo" }
                }
                """);

        assertEquals(HttpStatus.OK, exported.getStatusCode());
        assertNotNull(exported.getHeaders().getContentType());
        assertEquals("text", exported.getHeaders().getContentType().getType());
        assertEquals("csv", exported.getHeaders().getContentType().getSubtype());
        assertTrue(exported.getHeaders().getFirst(HttpHeaders.CONTENT_DISPOSITION).contains("funcionarios.csv"));
        assertEquals("2", exported.getHeaders().getFirst("X-Export-Row-Count"));
        assertEquals("""
                \uFEFFsep=;\r
                "Status";"Salario";"Admissao"\r
                "Inativo";"R$\u00A095.000,00";"01/02/2010"\r
                "Ativo";"R$\u00A041.000,00";"13/06/2022"
                """.stripTrailing(), exported.getBody());
    }

    @Test
    void shouldKeepRawFuncionarioValuesWhenFormattingIsDisabled() {
        ResponseEntity<String> exported = postExport("""
                {
                  "format": "csv",
                  "scope": "currentPage",
                  "includeHeaders": true,
                  "applyFormatting": false,
                  "fields": [
                    { "key": "ativo", "label": "Status", "visible": true, "exportable": true },
                    { "key": "salario", "label": "Salario", "visible": true, "exportable": true },
                    { "key": "dataAdmissao", "label": "Admissao", "visible": true, "exportable": true }
                  ],
                  "pagination": { "pageIndex": 0, "pageNumber": 0, "pageSize": 1 },
                  "sort": [{ "field": "salario", "direction": "desc" }],
                  "formatOptions": { "csv": { "excelCompatibility": true } },
                  "localization": { "locale": "pt-BR", "timeZone": "America/Sao_Paulo" }
                }
                """);

        assertEquals(HttpStatus.OK, exported.getStatusCode());
        assertEquals("""
                \uFEFFsep=;\r
                "Status";"Salario";"Admissao"\r
                "false";"95000.00";"2010-02-01"
                """.stripTrailing(), exported.getBody());
    }

    @Test
    void shouldRejectFuncionarioExportWhenAnyRequestedFieldIsNotSupported() {
        ResponseEntity<String> exported = postExport("""
                {
                  "format": "csv",
                  "scope": "currentPage",
                  "fields": [
                    { "key": "salario", "label": "Salario", "visible": true, "exportable": true },
                    { "key": "campoInvalido", "label": "Campo invalido", "visible": true, "exportable": true }
                  ]
                }
                """);

        assertEquals(HttpStatus.BAD_REQUEST, exported.getStatusCode());
        assertTrue(exported.getBody().contains("One or more requested export fields are not supported by this resource."));
    }

    @Test
    void shouldExportFuncionariosExcelWithGovernedFormatting() throws Exception {
        ResponseEntity<byte[]> exported = postExportBytes("""
                {
                  "format": "excel",
                  "scope": "currentPage",
                  "includeHeaders": true,
                  "applyFormatting": true,
                  "fields": [
                    { "key": "ativo", "label": "Status", "visible": true, "exportable": true },
                    { "key": "salario", "label": "Salario", "visible": true, "exportable": true },
                    { "key": "dataAdmissao", "label": "Admissao", "visible": true, "exportable": true }
                  ],
                  "pagination": { "pageIndex": 0, "pageNumber": 0, "pageSize": 2 },
                  "sort": [{ "field": "salario", "direction": "desc" }],
                  "formatOptions": { "excel": { "sheetName": "Funcionarios", "freezeHeaders": true, "autoFitColumns": true } },
                  "localization": { "locale": "pt-BR", "timeZone": "America/Sao_Paulo" }
                }
                """);

        assertEquals(HttpStatus.OK, exported.getStatusCode());
        assertNotNull(exported.getHeaders().getContentType());
        assertEquals("application", exported.getHeaders().getContentType().getType());
        assertEquals("vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                exported.getHeaders().getContentType().getSubtype());
        assertTrue(exported.getHeaders().getFirst(HttpHeaders.CONTENT_DISPOSITION).contains("funcionarios.xlsx"));
        assertEquals("2", exported.getHeaders().getFirst("X-Export-Row-Count"));
        assertNotNull(exported.getBody());

        try (Workbook workbook = new XSSFWorkbook(new ByteArrayInputStream(exported.getBody()))) {
            var sheet = workbook.getSheet("Funcionarios");
            assertNotNull(sheet);
            assertEquals("Status", sheet.getRow(0).getCell(0).getStringCellValue());
            assertEquals("Salario", sheet.getRow(0).getCell(1).getStringCellValue());
            assertEquals("Admissao", sheet.getRow(0).getCell(2).getStringCellValue());
            assertEquals("Inativo", sheet.getRow(1).getCell(0).getStringCellValue());
            assertEquals("R$\u00A095.000,00", sheet.getRow(1).getCell(1).getStringCellValue());
            assertEquals("01/02/2010", sheet.getRow(1).getCell(2).getStringCellValue());
            assertEquals("Ativo", sheet.getRow(2).getCell(0).getStringCellValue());
            assertEquals("R$\u00A041.000,00", sheet.getRow(2).getCell(1).getStringCellValue());
            assertEquals("13/06/2022", sheet.getRow(2).getCell(2).getStringCellValue());
        }
    }

    @Test
    void shouldAdvertiseOnlyRegisteredFuncionarioExportFormats() throws Exception {
        ResponseEntity<String> response = restTemplate.exchange(
                "/api/human-resources/funcionarios/capabilities",
                HttpMethod.GET,
                authorizedJson(null, jwtTokenService.generate("admin", "ADMIN")),
                String.class
        );

        assertEquals(HttpStatus.OK, response.getStatusCode());
        JsonNode formats = objectMapper.readTree(response.getBody())
                .path("operations")
                .path("export")
                .path("formats");
        assertEquals(3, formats.size());
        assertEquals("csv", formats.get(0).asText());
        assertEquals("json", formats.get(1).asText());
        assertEquals("excel", formats.get(2).asText());
    }

    private ResponseEntity<String> postExport(String json) {
        return restTemplate.exchange(
                "/api/human-resources/funcionarios/export",
                HttpMethod.POST,
                authorizedJson(json, jwtTokenService.generate("admin", "ADMIN")),
                String.class
        );
    }

    private ResponseEntity<byte[]> postExportBytes(String json) {
        return restTemplate.exchange(
                "/api/human-resources/funcionarios/export",
                HttpMethod.POST,
                authorizedJson(json, jwtTokenService.generate("admin", "ADMIN")),
                byte[].class
        );
    }

    private HttpEntity<String> authorizedJson(String json, String token) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.add(HttpHeaders.COOKIE, "SESSION=" + token);
        return new HttpEntity<>(json, headers);
    }
}
