package com.example.praxis.apiquickstart.config;

import com.example.praxis.apiquickstart.ApiQuickstartApplication;
import com.example.praxis.apiquickstart.security.JwtTokenService;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@SpringBootTest(
        classes = ApiQuickstartApplication.class,
        webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
        properties = {
                "app.rate-limit.enabled=false",
                "app.security.config-origin-restriction.enabled=false",
                "app.security.read-open=true",
                "app.security.write-disabled=false",
                "app.security.schemas-aggregator.enabled=true",
                "app.security.csrf.disable=true",
                "app.session.cookie-name=SESSION",
                "app.session.secure=false",
                "app.session.samesite=Lax",
                "praxis.stats.enabled=true",
                "praxis.ai.provider=mock",
                "spring.ai.embedding.provider=mock",
                "spring.ai.openai.api-key=dummy",
                "praxis.ai.rag.vector-store.enabled=false",
                "praxis.ai.registry.bootstrap.enabled=false",
                "praxis.ai.registry.health.enabled=false",
                "spring.ai.vectorstore.pgvector.initialize-schema=false",
                "spring.ai.vectorstore.pgvector.vector-table-validations-enabled=false",
                "spring.flyway.enabled=false",
                "spring.datasource.url=jdbc:h2:mem:quickstart_legacy_backed_resource_api;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
                "spring.datasource.driver-class-name=org.h2.Driver",
                "spring.datasource.username=sa",
                "spring.datasource.password=",
                "config.datasource.url=jdbc:h2:mem:quickstart_legacy_backed_resource_config;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
                "config.datasource.driver-class-name=org.h2.Driver",
                "config.datasource.username=sa",
                "config.datasource.password=",
                "spring.jpa.hibernate.ddl-auto=none"
        }
)
class LegacyBackedResourcePilotIntegrationTest {

    private static final String BASE_PATH = "/api/human-resources/legacy-pay-codes";

    @Autowired
    private TestRestTemplate restTemplate;

    @Autowired
    @Qualifier("apiJdbcTemplate")
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private JwtTokenService jwtTokenService;

    @MockBean(name = "ragVectorStore")
    private VectorStore ragVectorStore;

    @BeforeEach
    void seedLegacyPayCodeTable() {
        jdbcTemplate.execute("drop table if exists public.legacy_pay_codes");
        jdbcTemplate.execute("""
                create table public.legacy_pay_codes (
                    id integer generated by default as identity primary key,
                    code varchar(40) not null,
                    description varchar(240) not null,
                    payroll_category varchar(80) not null,
                    status varchar(40) not null,
                    active boolean not null
                )
                """);
        jdbcTemplate.update("""
                insert into public.legacy_pay_codes
                    (code, description, payroll_category, status, active)
                values
                    ('BASE-HAZARD', 'Hazard pay baseline', 'additional-pay', 'ACTIVE', true)
                """);
    }

    @Test
    void legacyBackedResourcePublishesCanonicalCrudDuplicateDraftAndHypermedia() throws Exception {
        JsonNode capabilities = body(restTemplate.getForEntity(BASE_PATH + "/capabilities", String.class));
        assertTrue(capabilities.path("canonicalOperations").path("create").asBoolean());
        assertTrue(capabilities.path("canonicalOperations").path("update").asBoolean());
        assertTrue(capabilities.path("canonicalOperations").path("delete").asBoolean());
        assertTrue(capabilities.path("canonicalOperations").path("duplicate-draft").asBoolean());
        assertTrue(capabilities.path("operations").path("duplicate-draft").path("supported").asBoolean());
        assertEquals("POST", capabilities.path("operations").path("duplicate-draft").path("preferredMethod").asText());

        JsonNode created = bodyCreated(restTemplate.exchange(
                BASE_PATH,
                HttpMethod.POST,
                authorizedJson("""
                        {
                          "code": "EVT-REMOTE",
                          "description": "Remote work allowance",
                          "payrollCategory": "benefit",
                          "status": "active",
                          "active": true
                        }
                        """),
                String.class
        ));
        int createdId = created.path("data").path("id").asInt();
        assertEquals("ACTIVE", created.path("data").path("status").asText());

        JsonNode detail = body(restTemplate.getForEntity(BASE_PATH + "/" + createdId, String.class));
        assertNotNull(findLinkHref(detail, "duplicate-draft"));
        assertNotNull(findLinkHref(detail, "update"));
        assertNotNull(findLinkHref(detail, "delete"));

        JsonNode itemCapabilities = body(restTemplate.getForEntity(BASE_PATH + "/" + createdId + "/capabilities", String.class));
        assertTrue(itemCapabilities.path("operations").path("duplicate-draft").path("availability").path("allowed").asBoolean());

        JsonNode actionCatalog = body(restTemplate.getForEntity(
                "/schemas/actions?resource=human-resources.legacy-pay-codes",
                String.class
        ));
        JsonNode duplicateDraftAction = findById(actionCatalog.path("actions"), "duplicate-draft");
        assertNotNull(duplicateDraftAction);
        JsonNode duplicateDraftRequestSchema = body(restTemplate.getForEntity(
                duplicateDraftAction.path("requestSchemaUrl").asText(),
                String.class
        ));
        assertEquals("object", duplicateDraftRequestSchema.path("type").asText());
        assertTrue(duplicateDraftRequestSchema.path("properties").isObject(), duplicateDraftRequestSchema.toPrettyString());
        JsonNode duplicateDraftResponseSchema = body(restTemplate.getForEntity(
                duplicateDraftAction.path("responseSchemaUrl").asText(),
                String.class
        ));
        assertEquals("object", duplicateDraftResponseSchema.path("type").asText());
        assertTrue(duplicateDraftResponseSchema.path("properties").has("code"),
                duplicateDraftResponseSchema.toPrettyString());

        JsonNode responseSchema = body(restTemplate.getForEntity(
                "/schemas/filtered?path=/api/human-resources/legacy-pay-codes/%7Bid%7D&operation=get&schemaType=response",
                String.class
        ));
        JsonNode codeField = responseSchema.path("properties").path("code");
        assertEquals("Codigo operacional reconhecido pelo backend legado de folha para classificar eventos e rubricas.",
                codeField.path("description").asText());

        JsonNode surfaces = body(restTemplate.getForEntity(
                "/schemas/surfaces?resource=human-resources.legacy-pay-codes",
                String.class
        ));
        JsonNode auditSurface = findById(surfaces.path("surfaces"), "audit-lines");
        assertNotNull(auditSurface);
        assertEquals("ITEM", auditSurface.path("scope").asText());
        assertEquals("READ_PROJECTION", auditSurface.path("kind").asText());
        assertEquals("COLLECTION", auditSurface.path("responseCardinality").asText());
        assertEquals("human-resources.legacy-pay-code-audit-lines",
                auditSurface.path("relatedResource").path("childResourceKey").asText());
        assertEquals("/api/human-resources/legacy-pay-code-audit-lines",
                auditSurface.path("relatedResource").path("childResourcePath").asText());
        assertEquals("payCodeId", auditSurface.path("relatedResource").path("childParentField").asText());
        assertTrue(auditSurface.path("relatedResource").path("selectable").asBoolean());
        assertEquals("auditLineId", auditSurface.path("relatedResource").path("selectionKeyField").asText());
        assertEquals("[]", auditSurface.path("relatedResource").path("childOperations").toString());
        assertTrue(auditSurface.path("schemaUrl").asText().contains("audit-lines"));

        JsonNode itemSurfaces = body(restTemplate.getForEntity(BASE_PATH + "/" + createdId + "/surfaces", String.class));
        JsonNode itemAuditSurface = findById(itemSurfaces.path("surfaces"), "audit-lines");
        assertNotNull(itemAuditSurface);
        assertTrue(itemAuditSurface.path("availability").path("allowed").asBoolean());

        JsonNode auditLines = body(restTemplate.getForEntity(BASE_PATH + "/" + createdId + "/audit-lines", String.class));
        assertEquals(createdId, auditLines.path("data").get(0).path("payCodeId").asInt());
        assertEquals("AUD-" + createdId + "-001", auditLines.path("data").get(0).path("auditLineId").asText());

        JsonNode auditSchema = body(restTemplate.getForEntity(
                auditSurface.path("schemaUrl").asText(),
                String.class
        ));
        assertTrue(auditSchema.path("properties").has("auditLineId"), auditSchema.toPrettyString());
        assertTrue(auditSchema.path("properties").has("payCodeId"), auditSchema.toPrettyString());
        assertEquals("auditLineId", auditSchema.path("x-ui").path("resource").path("idField").asText());

        JsonNode draft = body(restTemplate.exchange(
                BASE_PATH + "/" + createdId + "/duplicate-draft",
                HttpMethod.POST,
                authorizedJson("{}"),
                String.class
        ));
        assertEquals("DRAFT", draft.path("data").path("status").asText());
        assertFalse(draft.path("data").path("active").asBoolean());
        JsonNode schemaLinks = draft.path("_links").path("schema");
        assertTrue(schemaLinks.isArray(), draft.toPrettyString());
        assertTrue(containsSchemaType(schemaLinks, "request"), draft.toPrettyString());
        assertTrue(containsSchemaType(schemaLinks, "response"), draft.toPrettyString());

        ResponseEntity<String> updated = restTemplate.exchange(
                BASE_PATH + "/" + createdId,
                HttpMethod.PUT,
                authorizedJson("""
                        {
                          "code": "EVT-REMOTE",
                          "description": "Remote work allowance revised",
                          "payrollCategory": "benefit",
                          "status": "active",
                          "active": true
                        }
                        """),
                String.class
        );
        assertEquals(HttpStatus.OK, updated.getStatusCode());

        ResponseEntity<String> deleted = restTemplate.exchange(
                BASE_PATH + "/" + createdId,
                HttpMethod.DELETE,
                authorizedJson("{}"),
                String.class
        );
        assertEquals(HttpStatus.NO_CONTENT, deleted.getStatusCode());
    }

    private JsonNode body(ResponseEntity<String> response) throws Exception {
        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertNotNull(response.getBody());
        return objectMapper.readTree(response.getBody());
    }

    private JsonNode bodyCreated(ResponseEntity<String> response) throws Exception {
        assertEquals(HttpStatus.CREATED, response.getStatusCode());
        assertNotNull(response.getBody());
        return objectMapper.readTree(response.getBody());
    }

    private HttpEntity<String> authorizedJson(String json) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.add(HttpHeaders.COOKIE, "SESSION=" + jwtTokenService.generate("admin", "ADMIN"));
        return new HttpEntity<>(json, headers);
    }

    private String findLinkHref(JsonNode envelope, String rel) {
        JsonNode links = envelope.path("_links");
        if (!links.isObject()) {
            return null;
        }
        JsonNode link = links.path(rel);
        if (link.isObject()) {
            return link.path("href").asText(null);
        }
        return null;
    }

    private boolean containsSchemaType(JsonNode links, String schemaType) {
        if (!links.isArray()) {
            return false;
        }
        for (JsonNode link : links) {
            String href = link.path("href").asText();
            if (href.contains("schemaType=" + schemaType)) {
                return true;
            }
        }
        return false;
    }

    private JsonNode findById(JsonNode array, String id) {
        if (!array.isArray()) {
            return null;
        }
        for (JsonNode item : array) {
            if (id.equals(item.path("id").asText())) {
                return item;
            }
        }
        return null;
    }
}
