-- Prepara o dominio de procurement para o piloto de Entity Lookup.
-- Idempotente para bancos novos criados pelo fluxo db/init/*.sql.

CREATE TABLE IF NOT EXISTS public.procurement_companies (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(255) NOT NULL,
    legal_name varchar(255) NOT NULL,
    document_number varchar(255),
    city varchar(255),
    state varchar(255),
    status varchar(255),
    disabled_reason varchar(255)
);

CREATE TABLE IF NOT EXISTS public.procurement_suppliers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL,
    code varchar(255) NOT NULL,
    legal_name varchar(255) NOT NULL,
    document_number varchar(255),
    homologation_status varchar(255),
    risk_level varchar(255),
    status varchar(255),
    disabled_reason varchar(255)
);

CREATE TABLE IF NOT EXISTS public.procurement_contracts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL,
    supplier_id integer NOT NULL,
    number varchar(255) NOT NULL,
    supplier_name varchar(255),
    currency varchar(255),
    valid_until date,
    status varchar(255),
    disabled_reason varchar(255)
);

CREATE TABLE IF NOT EXISTS public.procurement_products (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL,
    contract_id integer,
    sku varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    category_name varchar(255),
    stock_available integer,
    unit_of_measure varchar(255),
    status varchar(255),
    disabled_reason varchar(255)
);

CREATE TABLE IF NOT EXISTS public.procurement_purchase_orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL,
    supplier_id integer NOT NULL,
    contract_id integer,
    product_id integer NOT NULL,
    order_date date,
    currency varchar(255),
    quantity integer
);

CREATE INDEX IF NOT EXISTS idx_procurement_suppliers_company
    ON public.procurement_suppliers (company_id);

CREATE INDEX IF NOT EXISTS idx_procurement_contracts_company_supplier
    ON public.procurement_contracts (company_id, supplier_id);

CREATE INDEX IF NOT EXISTS idx_procurement_products_company_contract
    ON public.procurement_products (company_id, contract_id);

INSERT INTO public.procurement_companies
    (id, code, legal_name, document_number, city, state, status, disabled_reason)
VALUES
    (1, 'EMP-001', 'Praxis Brasil Ltda', '11.222.333/0001-44', 'Sao Paulo', 'SP', 'ACTIVE', NULL),
    (2, 'EMP-003', 'Praxis Nordeste', '11.222.333/0003-06', 'Recife', 'PE', 'INACTIVE', 'Empresa inativa desde 01/2026')
ON CONFLICT (id) DO UPDATE SET
    code = EXCLUDED.code,
    legal_name = EXCLUDED.legal_name,
    document_number = EXCLUDED.document_number,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    status = EXCLUDED.status,
    disabled_reason = EXCLUDED.disabled_reason;

INSERT INTO public.procurement_suppliers
    (id, company_id, code, legal_name, document_number, homologation_status, risk_level, status, disabled_reason)
VALUES
    (10, 1, 'FOR-8742', 'ACME Suprimentos Ltda', '12.345.678/0001-90', 'APPROVED', 'LOW', 'ACTIVE', NULL),
    (11, 1, 'FOR-9921', 'Fornecedor Bloqueado S.A.', '98.765.432/0001-10', 'SUSPENDED', 'HIGH', 'BLOCKED', 'Fornecedor bloqueado para novos pedidos'),
    (12, 2, 'FOR-1000', 'ACME Nordeste', '55.000.111/0001-00', 'APPROVED', 'LOW', 'ACTIVE', NULL)
ON CONFLICT (id) DO UPDATE SET
    company_id = EXCLUDED.company_id,
    code = EXCLUDED.code,
    legal_name = EXCLUDED.legal_name,
    document_number = EXCLUDED.document_number,
    homologation_status = EXCLUDED.homologation_status,
    risk_level = EXCLUDED.risk_level,
    status = EXCLUDED.status,
    disabled_reason = EXCLUDED.disabled_reason;

INSERT INTO public.procurement_contracts
    (id, company_id, supplier_id, number, supplier_name, currency, valid_until, status, disabled_reason)
VALUES
    (20, 1, 10, 'CTR-2026-001', 'ACME Suprimentos Ltda', 'BRL', DATE '2026-12-31', 'SIGNED', NULL),
    (21, 1, 10, 'CTR-2025-009', 'ACME Suprimentos Ltda', 'BRL', DATE '2025-12-31', 'EXPIRED', 'Contrato expirado em 31/12/2025')
ON CONFLICT (id) DO UPDATE SET
    company_id = EXCLUDED.company_id,
    supplier_id = EXCLUDED.supplier_id,
    number = EXCLUDED.number,
    supplier_name = EXCLUDED.supplier_name,
    currency = EXCLUDED.currency,
    valid_until = EXCLUDED.valid_until,
    status = EXCLUDED.status,
    disabled_reason = EXCLUDED.disabled_reason;

INSERT INTO public.procurement_products
    (id, company_id, contract_id, sku, name, category_name, stock_available, unit_of_measure, status, disabled_reason)
VALUES
    (30, 1, 20, 'PRD-00123', 'Notebook Dell Latitude', 'Equipamentos', 12, 'UN', 'ACTIVE', NULL),
    (31, 1, 20, 'PRD-00444', 'Docking Station Legacy', 'Equipamentos', 0, 'UN', 'BLOCKED', 'Produto sem estoque liberado')
ON CONFLICT (id) DO UPDATE SET
    company_id = EXCLUDED.company_id,
    contract_id = EXCLUDED.contract_id,
    sku = EXCLUDED.sku,
    name = EXCLUDED.name,
    category_name = EXCLUDED.category_name,
    stock_available = EXCLUDED.stock_available,
    unit_of_measure = EXCLUDED.unit_of_measure,
    status = EXCLUDED.status,
    disabled_reason = EXCLUDED.disabled_reason;

INSERT INTO public.procurement_purchase_orders
    (id, company_id, supplier_id, contract_id, product_id, order_date, currency, quantity)
VALUES
    (40, 1, 10, 20, 30, DATE '2026-04-15', 'BRL', 2)
ON CONFLICT (id) DO UPDATE SET
    company_id = EXCLUDED.company_id,
    supplier_id = EXCLUDED.supplier_id,
    contract_id = EXCLUDED.contract_id,
    product_id = EXCLUDED.product_id,
    order_date = EXCLUDED.order_date,
    currency = EXCLUDED.currency,
    quantity = EXCLUDED.quantity;

SELECT setval(pg_get_serial_sequence('public.procurement_companies', 'id'), (SELECT MAX(id) FROM public.procurement_companies), true);
SELECT setval(pg_get_serial_sequence('public.procurement_suppliers', 'id'), (SELECT MAX(id) FROM public.procurement_suppliers), true);
SELECT setval(pg_get_serial_sequence('public.procurement_contracts', 'id'), (SELECT MAX(id) FROM public.procurement_contracts), true);
SELECT setval(pg_get_serial_sequence('public.procurement_products', 'id'), (SELECT MAX(id) FROM public.procurement_products), true);
SELECT setval(pg_get_serial_sequence('public.procurement_purchase_orders', 'id'), (SELECT MAX(id) FROM public.procurement_purchase_orders), true);
