package com.example.praxis.apiquickstart.hr;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/** Restores the official public demo and proves the HR analytics seed on PostgreSQL. */
@Testcontainers(disabledWithoutDocker = true)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class AbsenceAnalyticsDemoSeedPostgresTest {

    private static final String DEMO_MARKER = "PRAXIS_DEMO_HR_ANALYTICS_20260715";

    @Container
    static final PostgreSQLContainer<?> POSTGRES = new PostgreSQLContainer<>("postgres:16-alpine");

    @BeforeAll
    void restoreDemoAndApplyOperationalMigrationsTwice() throws Exception {
        try (Connection connection = connection(); Statement statement = connection.createStatement()) {
            statement.execute(Files.readString(Path.of(
                    "src/test/resources/absence-analytics-lab/postgres-operational-schema.sql")));
            statement.execute("""
                    alter table public.ferias_afastamentos
                        alter column id add generated by default as identity,
                        add column tipo varchar(40),
                        add column observacoes varchar(255)
                    """);
            statement.execute("""
                    create table public.praxis_demo_dataset_guard (
                        dataset_key varchar(80) primary key,
                        dataset_fingerprint varchar(120) not null
                    )
                    """);
            statement.execute("""
                    insert into public.praxis_demo_dataset_guard (dataset_key, dataset_fingerprint)
                    values ('praxis-public-demo', 'praxis-public-demo-2026-07-15')
                    """);
            insertPublicDemoDepartments(connection);
            insertPublicDemoEmployees(connection);
            insertPublicDemoAbsences(connection);
            statement.execute("""
                    select setval(
                        pg_get_serial_sequence('public.ferias_afastamentos', 'id'),
                        (select max(id) from public.ferias_afastamentos),
                        true
                    )
                    """);
        }

        JdbcSqlRunnerProcess.Execution execution = run(
                "db/operational-migrations/V20260714_001__historical_department_assignments.sql",
                "db/demo-seeds/public-demo/absence-analytics/V20260715_006__absence_analytics_demo_seed.sql",
                "db/operational-migrations/V20260715_005__absence_analytics_unique_days_policy.sql");
        assertEquals(0, execution.exitCode(), execution.output());
        JdbcSqlRunnerProcess.Execution idempotentReplay = run(
                "db/demo-seeds/public-demo/absence-analytics/V20260715_006__absence_analytics_demo_seed.sql");
        assertEquals(0, idempotentReplay.exitCode(), idempotentReplay.output());
    }

    @Test
    void shouldSeedAssignmentsAndAbsencesIdempotentlyWithFullAttribution() throws Exception {
        try (Connection connection = connection(); Statement statement = connection.createStatement()) {
            assertEquals(53, scalarLong(statement, """
                    select count(*)
                    from public.funcionario_lotacoes_departamento
                    where funcionario_id between 1 and 50
                    """));
            assertEquals(50, scalarLong(statement, """
                    select count(distinct funcionario_id)
                    from public.funcionario_lotacoes_departamento
                    where funcionario_id between 1 and 50
                    """));
            assertEquals(100, scalarLong(statement, """
                    select count(*)
                    from public.ferias_afastamentos
                    where observacoes <> '%s'
                    """.formatted(DEMO_MARKER)));
            assertEquals(11, scalarLong(statement, """
                    select count(*)
                    from public.ferias_afastamentos
                    where observacoes = '%s'
                    """.formatted(DEMO_MARKER)));
            assertEquals(0, scalarLong(statement, """
                    select count(*)
                    from public.ferias_afastamentos fa
                    where exists (
                        select 1
                        from generate_series(fa.data_inicio, fa.data_fim, interval '1 day') as day(value)
                        where not exists (
                            select 1
                            from public.funcionario_lotacoes_departamento assignment
                            where assignment.funcionario_id = fa.funcionario_id
                              and assignment.effective_from <= day.value::date
                              and coalesce(assignment.effective_to, 'infinity'::date) > day.value::date
                        )
                    )
                    """));
            assertEquals(11, scalarLong(statement, """
                    select dias_afastado
                    from public.vw_analytics_afastamentos
                    where funcionario_id = 8
                      and competencia = date '2026-06-01'
                    """));
        }
    }

    @Test
    void shouldRefuseCorporateLikeDatabaseWithReusableIdsWithoutWritingAnalyticsSeed() throws Exception {
        String corporateDatabase = "absence_analytics_corporate_probe";
        try (Connection connection = connection(); Statement statement = connection.createStatement()) {
            statement.execute("drop database if exists " + corporateDatabase);
            statement.execute("create database " + corporateDatabase);
        }
        try (Connection connection = connection(corporateDatabase); Statement statement = connection.createStatement()) {
            statement.execute(Files.readString(Path.of(
                    "src/test/resources/absence-analytics-lab/postgres-operational-schema.sql")));
            statement.execute("""
                    alter table public.ferias_afastamentos
                        alter column id add generated by default as identity,
                        add column tipo varchar(40),
                        add column observacoes varchar(255)
                    """);
            statement.execute("""
                    create table public.praxis_demo_dataset_guard (
                        dataset_key varchar(80) primary key,
                        dataset_fingerprint varchar(120) not null
                    )
                    """);
            statement.execute("""
                    insert into public.praxis_demo_dataset_guard (dataset_key, dataset_fingerprint)
                    values ('praxis-public-demo', 'praxis-public-demo-2026-07-15')
                    """);
            insertCorporateLikeDepartments(connection);
            insertCorporateLikeEmployees(connection);
        }

        JdbcSqlRunnerProcess.Execution migration = runInDatabase(corporateDatabase,
                "db/operational-migrations/V20260714_001__historical_department_assignments.sql");
        assertEquals(0, migration.exitCode(), migration.output());

        try (Connection connection = connection(corporateDatabase); Statement statement = connection.createStatement()) {
            long assignmentsBefore = scalarLong(statement, "select count(*) from public.funcionario_lotacoes_departamento");
            long eventsBefore = scalarLong(statement, "select count(*) from public.ferias_afastamentos");
            JdbcSqlRunnerProcess.Execution guardedSeed = runInDatabase(corporateDatabase,
                    "db/demo-seeds/public-demo/absence-analytics/V20260715_006__absence_analytics_demo_seed.sql");
            assertNotEquals(0, guardedSeed.exitCode(), guardedSeed.output());
            assertTrue(guardedSeed.output().contains("PRAXIS_DEMO_GUARD"), guardedSeed.output());
            assertEquals(assignmentsBefore, scalarLong(statement,
                    "select count(*) from public.funcionario_lotacoes_departamento"));
            assertEquals(eventsBefore, scalarLong(statement,
                    "select count(*) from public.ferias_afastamentos"));
        }
    }

    private static JdbcSqlRunnerProcess.Execution run(String... paths) throws Exception {
        return JdbcSqlRunnerProcess.run(
                POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword(),
                java.util.Arrays.stream(paths).map(Path::of).toArray(Path[]::new));
    }

    private static JdbcSqlRunnerProcess.Execution runInDatabase(String database, String... paths) throws Exception {
        return JdbcSqlRunnerProcess.run(
                jdbcUrl(database), POSTGRES.getUsername(), POSTGRES.getPassword(),
                java.util.Arrays.stream(paths).map(Path::of).toArray(Path[]::new));
    }

    private static void insertPublicDemoDepartments(Connection connection) throws Exception {
        List<String[]> rows = publicDemoCopyRows(
                "COPY public.departamentos (id, nome, codigo, responsavel_id) FROM stdin;");
        assertEquals(27, rows.size());
        try (PreparedStatement insert = connection.prepareStatement(
                "insert into public.departamentos (id, codigo, nome) values (?, ?, ?)")) {
            for (String[] row : rows) {
                insert.setInt(1, Integer.parseInt(row[0]));
                insert.setString(2, row[2]);
                insert.setString(3, row[1]);
                insert.addBatch();
            }
            insert.executeBatch();
        }
    }

    private static void insertPublicDemoEmployees(Connection connection) throws Exception {
        List<String[]> rows = publicDemoCopyRows(
                "COPY public.funcionarios (id, nome_completo, cpf, data_nascimento, email, telefone, salario, data_admissao, ativo, cargo_id, departamento_id, foto_perfil_url, estado_civil, pais_nascimento, cidade_nascimento) FROM stdin;");
        assertEquals(98, rows.size());
        try (PreparedStatement insert = connection.prepareStatement(
                "insert into public.funcionarios (id, nome_completo, cpf, email) values (?, ?, ?, ?)")) {
            for (String[] row : rows) {
                insert.setInt(1, Integer.parseInt(row[0]));
                insert.setString(2, row[1]);
                insert.setString(3, row[2]);
                insert.setString(4, row[4]);
                insert.addBatch();
            }
            insert.executeBatch();
        }
    }

    private static void insertCorporateLikeDepartments(Connection connection) throws Exception {
        try (PreparedStatement insert = connection.prepareStatement(
                "insert into public.departamentos (id, codigo, nome) values (?, ?, ?)")) {
            for (int id = 1; id <= 27; id++) {
                insert.setInt(1, id);
                insert.setString(2, "CORP-" + id);
                insert.setString(3, "Departamento Corporativo " + id);
                insert.addBatch();
            }
            insert.executeBatch();
        }
    }

    private static void insertCorporateLikeEmployees(Connection connection) throws Exception {
        try (PreparedStatement insert = connection.prepareStatement(
                "insert into public.funcionarios (id, nome_completo, cpf, email) values (?, ?, ?, ?)")) {
            for (int id = 1; id <= 50; id++) {
                insert.setInt(1, id);
                insert.setString(2, "Pessoa Corporativa " + id);
                insert.setString(3, String.format("700000%05d", id));
                insert.setString(4, "pessoa-" + id + "@corporate.example");
                insert.addBatch();
            }
            insert.executeBatch();
        }
    }

    private static void insertPublicDemoAbsences(Connection connection) throws Exception {
        List<String[]> rows = publicDemoCopyRows(
                "COPY public.ferias_afastamentos (id, tipo, data_inicio, data_fim, observacoes, funcionario_id) FROM stdin;");
        assertEquals(100, rows.size());
        try (PreparedStatement insert = connection.prepareStatement("""
                insert into public.ferias_afastamentos (
                    id, tipo, data_inicio, data_fim, observacoes, funcionario_id
                ) values (?, ?, ?, ?, ?, ?)
                """)) {
            for (String[] row : rows) {
                insert.setInt(1, Integer.parseInt(row[0]));
                insert.setString(2, row[1]);
                insert.setObject(3, LocalDate.parse(row[2]));
                insert.setObject(4, LocalDate.parse(row[3]));
                insert.setString(5, copyValue(row[4]));
                insert.setInt(6, Integer.parseInt(row[5]));
                insert.addBatch();
            }
            insert.executeBatch();
        }
    }

    private static List<String[]> publicDemoCopyRows(String header) throws Exception {
        List<String[]> rows = new ArrayList<>();
        boolean reading = false;
        for (String line : Files.readAllLines(Path.of("db/dump/public-demo-seed.sql"))) {
            if (!reading) {
                reading = header.equals(line);
                continue;
            }
            if ("\\.".equals(line)) {
                return rows;
            }
            rows.add(line.split("\\t", -1));
        }
        throw new IllegalStateException("COPY section not found or incomplete: " + header);
    }

    private static String copyValue(String value) {
        return "\\N".equals(value) ? null : value;
    }

    private static Connection connection() throws Exception {
        return DriverManager.getConnection(POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
    }

    private static Connection connection(String database) throws Exception {
        return DriverManager.getConnection(jdbcUrl(database), POSTGRES.getUsername(), POSTGRES.getPassword());
    }

    private static String jdbcUrl(String database) {
        String jdbcUrl = POSTGRES.getJdbcUrl();
        int queryStart = jdbcUrl.indexOf('?');
        int databaseEnd = queryStart < 0 ? jdbcUrl.length() : queryStart;
        int databaseStart = jdbcUrl.lastIndexOf('/', databaseEnd - 1) + 1;
        return jdbcUrl.substring(0, databaseStart) + database + jdbcUrl.substring(databaseEnd);
    }

    private static long scalarLong(Statement statement, String sql) throws Exception {
        try (ResultSet result = statement.executeQuery(sql)) {
            result.next();
            return result.getLong(1);
        }
    }
}
