create table if not exists public.legacy_pay_codes (
    id integer generated by default as identity primary key,
    code varchar(40) not null,
    description varchar(240) not null,
    payroll_category varchar(80) not null,
    status varchar(40) not null,
    active boolean not null
);

insert into public.legacy_pay_codes (code, description, payroll_category, status, active)
select code, description, payroll_category, status, active
from (
    values
        ('BASE-HAZARD', 'Hazard pay baseline', 'additional-pay', 'ACTIVE', true),
        ('REMOTE-WORK', 'Remote work allowance', 'benefit', 'ACTIVE', true),
        ('RETRO-DISC', 'Retroactive discount adjustment', 'discount', 'DRAFT', true)
) as seed(code, description, payroll_category, status, active)
where not exists (
    select 1
    from public.legacy_pay_codes existing
    where existing.code = seed.code
);
