CREATE TABLE domain_rule_change_workspace (
    id UUID PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    environment VARCHAR(128) NOT NULL,
    rule_key VARCHAR(512) NOT NULL,
    base_definition_id UUID NOT NULL,
    base_definition_version INTEGER NOT NULL,
    base_definition_hash VARCHAR(64) NOT NULL,
    promoted_definition_id UUID,
    submitted_test_run_id UUID,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    draft_condition JSONB,
    draft_parameters JSONB NOT NULL,
    rationale TEXT,
    etag UUID NOT NULL,
    revision BIGINT NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE domain_rule_test_scenario (
    id UUID PRIMARY KEY,
    workspace_id UUID NOT NULL REFERENCES domain_rule_change_workspace(id) ON DELETE CASCADE,
    tenant_id VARCHAR(128) NOT NULL,
    environment VARCHAR(128) NOT NULL,
    scenario_key VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    facts JSONB NOT NULL,
    expected_decision VARCHAR(32) NOT NULL,
    expected_output JSONB,
    expected_reason_codes JSONB NOT NULL,
    expected_effect_intents JSONB NOT NULL,
    status VARCHAR(32) NOT NULL,
    etag UUID NOT NULL,
    revision BIGINT NOT NULL,
    created_by VARCHAR(255) NOT NULL,
    updated_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_policy_v59_scenario_key UNIQUE (workspace_id, scenario_key)
);

CREATE TABLE domain_rule_test_run (
    id UUID PRIMARY KEY,
    workspace_id UUID NOT NULL REFERENCES domain_rule_change_workspace(id) ON DELETE RESTRICT,
    tenant_id VARCHAR(128) NOT NULL,
    environment VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(180) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    workspace_revision BIGINT NOT NULL,
    base_definition_hash VARCHAR(64) NOT NULL,
    evaluated_at TIMESTAMPTZ NOT NULL,
    user_time_zone VARCHAR(128) NOT NULL,
    active_snapshot_key VARCHAR(128),
    active_snapshot_content_hash VARCHAR(64),
    active_activation_revision BIGINT NOT NULL,
    baseline_evidence JSONB,
    result_summary JSONB NOT NULL,
    recorded_by VARCHAR(255) NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_policy_v59_test_run_idempotency
        UNIQUE (tenant_id, environment, workspace_id, idempotency_key)
);

ALTER TABLE domain_rule_change_workspace
    ADD CONSTRAINT fk_policy_v59_submitted_test_run
    FOREIGN KEY (submitted_test_run_id) REFERENCES domain_rule_test_run(id) ON DELETE RESTRICT;

CREATE TABLE domain_rule_test_run_result (
    id UUID PRIMARY KEY,
    test_run_id UUID NOT NULL REFERENCES domain_rule_test_run(id) ON DELETE RESTRICT,
    scenario_id UUID NOT NULL REFERENCES domain_rule_test_scenario(id) ON DELETE RESTRICT,
    scenario_key VARCHAR(255) NOT NULL,
    expected_decision VARCHAR(32) NOT NULL,
    candidate_decision VARCHAR(32) NOT NULL,
    active_decision VARCHAR(32) NOT NULL,
    comparison VARCHAR(32) NOT NULL,
    candidate_matches_expected BOOLEAN NOT NULL,
    active_matches_expected BOOLEAN NOT NULL,
    expected_output JSONB,
    candidate_output JSONB,
    active_output JSONB,
    candidate_output_matches_expected BOOLEAN NOT NULL,
    active_output_matches_expected BOOLEAN NOT NULL,
    expected_reason_codes JSONB NOT NULL,
    candidate_reason_codes JSONB NOT NULL,
    active_reason_codes JSONB NOT NULL,
    candidate_reason_codes_match_expected BOOLEAN NOT NULL,
    active_reason_codes_match_expected BOOLEAN NOT NULL,
    expected_effect_intents JSONB NOT NULL,
    candidate_effect_intents JSONB NOT NULL,
    active_effect_intents JSONB NOT NULL,
    candidate_effects_match_expected BOOLEAN NOT NULL,
    active_effects_match_expected BOOLEAN NOT NULL,
    candidate_plan_digest VARCHAR(64) NOT NULL,
    active_plan_digest VARCHAR(64) NOT NULL,
    facts_digest VARCHAR(64) NOT NULL,
    baseline_result JSONB,
    candidate_baseline_comparison VARCHAR(32),
    baseline_matches_expected BOOLEAN,
    baseline_output_matches_expected BOOLEAN,
    baseline_reason_codes_match_expected BOOLEAN,
    baseline_effects_match_expected BOOLEAN,
    operational_evidence JSONB,
    CONSTRAINT uq_policy_v59_test_run_scenario UNIQUE (test_run_id, scenario_id)
);
