package com.example.praxis.apiquickstart.rulelab;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.util.UUID;
import javax.sql.DataSource;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;

class ExtraordinaryBenefitOperationalEvidenceProbeTest {
    private JdbcTemplate jdbc;
    private ExtraordinaryBenefitOperationalEvidenceProbe probe;

    @BeforeEach
    void setUp() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:policy-probe-" + UUID.randomUUID()
                + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        jdbc = new JdbcTemplate(dataSource);
        createSchema(jdbc);
        probe = new ExtraordinaryBenefitOperationalEvidenceProbe(
                jdbc, new DataSourceTransactionManager((DataSource) dataSource));
    }

    @Test
    void observesOnlyDigestsAndCleansTheOwnedFixture() {
        String reference = "policy-studio-proof-" + UUID.randomUUID();
        var empty = probe.capture(reference);
        jdbc.update("""
                insert into public.extraordinary_benefit_request
                    (request_reference, reason_code, event_date, requested_amount, lifecycle_status,
                     recommended_amount, currency, snapshot_content_hash, facts_digest, plan_digest,
                     planned_effect_intent, effect_status, version)
                values (?, 'EMERGENCY', date '2026-08-14', 100.00, 'EVALUATED', 100.00, 'BRL',
                        ?, ?, ?, 'grant.effect-plan', 'PLANNED', 0)
                """, reference, "A".repeat(64), "B".repeat(64), "C".repeat(64));
        Long id = jdbc.queryForObject(
                "select id from public.extraordinary_benefit_request where request_reference = ?",
                Long.class, reference);
        jdbc.update("""
                insert into public.extraordinary_benefit_transformation_audit
                    (audit_id, benefit_request_id, operation_cardinality, proposal_identity_digest,
                     before_digest, after_digest, snapshot_content_hash, facts_digest, plan_digest, recorded_at)
                values (?, ?, 'SINGLE_ITEM', ?, ?, ?, ?, ?, ?, current_timestamp)
                """, UUID.randomUUID(), id, "D".repeat(64), "E".repeat(64), "F".repeat(64),
                "A".repeat(64), "B".repeat(64), "C".repeat(64));

        var populated = probe.capture(reference);
        assertThat(populated.stateDigest()).matches("[A-F0-9]{64}").isNotEqualTo(empty.stateDigest());
        assertThat(populated.effectLedgerDigest()).isEqualTo(empty.effectLedgerDigest());

        probe.cleanup(reference);

        assertThat(probe.capture(reference)).isEqualTo(empty);
        assertThat(jdbc.queryForObject(
                "select count(*) from public.extraordinary_benefit_request", Integer.class)).isZero();
        assertThat(jdbc.queryForObject(
                "select count(*) from public.extraordinary_benefit_transformation_audit", Integer.class)).isZero();
    }

    @Test
    void refusesToObserveOrDeleteAnUnownedBusinessReference() {
        assertThatThrownBy(() -> probe.capture("customer-reference"))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> probe.cleanup("customer-reference"))
                .isInstanceOf(IllegalArgumentException.class);
    }

    private void createSchema(JdbcTemplate jdbc) {
        jdbc.execute("create schema if not exists public");
        jdbc.execute("""
                create table public.extraordinary_benefit_request (
                    id bigint generated by default as identity primary key,
                    request_reference varchar(80) not null unique,
                    reason_code varchar(40) not null,
                    event_date date not null,
                    requested_amount numeric(15,2) not null,
                    lifecycle_status varchar(20) not null,
                    recommended_amount numeric(15,2) not null,
                    currency varchar(3) not null,
                    snapshot_content_hash varchar(64) not null,
                    facts_digest varchar(64) not null,
                    plan_digest varchar(64) not null,
                    planned_effect_intent varchar(120) not null,
                    effect_status varchar(20) not null,
                    version bigint not null)
                """);
        jdbc.execute("""
                create table public.extraordinary_benefit_transformation_audit (
                    audit_id uuid primary key,
                    benefit_request_id bigint not null,
                    operation_cardinality varchar(32) not null,
                    proposal_identity_digest varchar(64) not null,
                    before_digest varchar(64) not null,
                    after_digest varchar(64) not null,
                    snapshot_content_hash varchar(64) not null,
                    facts_digest varchar(64) not null,
                    plan_digest varchar(64) not null,
                    recorded_at timestamp not null)
                """);
        jdbc.execute("""
                create table public.extraordinary_benefit_grant_effect (
                    effect_execution_id uuid primary key,
                    benefit_request_id bigint not null,
                    intent_type varchar(120) not null,
                    amount numeric(15,2) not null,
                    currency varchar(3) not null,
                    revalidation_snapshot_content_hash varchar(64) not null,
                    revalidation_facts_digest varchar(64) not null,
                    revalidation_scope_digest varchar(64) not null)
                """);
    }
}
