package com.example.praxis.apiquickstart.rulelab;

import static org.assertj.core.api.Assertions.assertThat;

import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;
import java.util.UUID;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

/** Real-process PostgreSQL proof that the evidence projection never mutates append-only ledgers. */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class ExtraordinaryBenefitOperationalEvidenceProbePostgresTest {
    private EmbeddedPostgres postgres;
    private JdbcTemplate jdbc;
    private ExtraordinaryBenefitOperationalEvidenceProbe probe;

    @BeforeAll
    void startPostgres() throws Exception {
        postgres = EmbeddedPostgres.builder()
                .setCleanDataDirectory(true)
                .setRegisterShutdownHook(false)
                .start();
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                postgres.getJdbcUrl("postgres", "postgres"), "postgres", "");
        jdbc = new JdbcTemplate(dataSource);
        createSchema();
        probe = new ExtraordinaryBenefitOperationalEvidenceProbe(jdbc);
    }

    @AfterAll
    void stopPostgres() throws Exception {
        if (postgres != null) postgres.close();
    }

    @Test
    void observesOnlyTheCorrelatedFixtureWithoutDeletingImmutableAudit() {
        String owned = "policy-studio-proof-pg-" + UUID.randomUUID();
        String unrelated = "business-reference-1";
        insertRequest(unrelated);
        var empty = probe.capture(owned);
        insertRequest(owned);
        Long ownedId = jdbc.queryForObject(
                "select id from public.extraordinary_benefit_request where request_reference=?",
                Long.class, owned);
        jdbc.update("""
                insert into public.extraordinary_benefit_transformation_audit
                    (audit_id, benefit_request_id, operation_cardinality, proposal_identity_digest,
                     before_digest, after_digest, snapshot_content_hash, facts_digest, plan_digest, recorded_at)
                values (?, ?, 'SINGLE_ITEM', ?, ?, ?, ?, ?, ?, current_timestamp)
                """, UUID.randomUUID(), ownedId, "D".repeat(64), "E".repeat(64), "F".repeat(64),
                "A".repeat(64), "B".repeat(64), "C".repeat(64));

        var populated = probe.capture(owned);
        assertThat(populated.stateDigest()).isNotEqualTo(empty.stateDigest());
        assertThat(probe.capture(owned)).isEqualTo(populated);
        assertThat(jdbc.queryForObject(
                "select count(*) from public.extraordinary_benefit_transformation_audit where benefit_request_id=?",
                Integer.class, ownedId)).isOne();
        assertThat(jdbc.queryForObject(
                "select count(*) from public.extraordinary_benefit_request where request_reference=?",
                Integer.class, unrelated)).isOne();
    }

    private void insertRequest(String reference) {
        jdbc.update("""
                insert into public.extraordinary_benefit_request
                    (request_reference, reason_code, event_date, requested_amount, lifecycle_status,
                     recommended_amount, currency, snapshot_content_hash, facts_digest, plan_digest,
                     planned_effect_intent, effect_status, version)
                values (?, 'FAMILY_HARDSHIP', date '2026-08-14', 100.00, 'EVALUATED', 100.00, 'BRL',
                        ?, ?, ?, 'grant.effect-plan', 'PLANNED', 0)
                """, reference, "A".repeat(64), "B".repeat(64), "C".repeat(64));
    }

    private void createSchema() {
        jdbc.execute("""
                create table public.extraordinary_benefit_request (
                    id bigint generated by default as identity primary key,
                    request_reference varchar(80) not null unique,
                    reason_code varchar(40) not null, event_date date not null,
                    requested_amount numeric(15,2) not null, lifecycle_status varchar(20) not null,
                    recommended_amount numeric(15,2) not null, currency varchar(3) not null,
                    snapshot_content_hash varchar(64) not null, facts_digest varchar(64) not null,
                    plan_digest varchar(64) not null, planned_effect_intent varchar(120) not null,
                    effect_status varchar(20) not null, version bigint not null)
                """);
        jdbc.execute("""
                create table public.extraordinary_benefit_transformation_audit (
                    audit_id uuid primary key, benefit_request_id bigint not null,
                    operation_cardinality varchar(32) not null,
                    proposal_identity_digest varchar(64) not null,
                    before_digest varchar(64) not null, after_digest varchar(64) not null,
                    snapshot_content_hash varchar(64) not null, facts_digest varchar(64) not null,
                    plan_digest varchar(64) not null, recorded_at timestamptz not null)
                """);
        jdbc.execute("""
                create table public.extraordinary_benefit_grant_effect (
                    effect_execution_id uuid primary key, benefit_request_id bigint not null,
                    intent_type varchar(120) not null, amount numeric(15,2) not null,
                    currency varchar(3) not null, revalidation_snapshot_content_hash varchar(64) not null,
                    revalidation_facts_digest varchar(64) not null,
                    revalidation_scope_digest varchar(64) not null)
                """);
    }
}
